//! Localized (Simplified Chinese) labels for the enum variant dropdowns in the
//! Settings UI. Each table is parallel to the enum's `strum::VariantNames::VARIANTS`
//! order. Entries kept in English are proper nouns (keymaps, models, encodings).

/// Returns the Simplified Chinese labels for the enum rendered by a dropdown,
/// or `None` when the variants should stay in English (e.g. proper nouns).
///
/// Keyed on the enum's short type name (the last `::`-segment of `type_name`),
/// which is unique among the settings enums rendered as dropdowns.
pub(super) fn localized_enum_labels<T: 'static>() -> Option<&'static [&'static str]> {
    let short = std::any::type_name::<T>().rsplit("::").next()?;
    match short {
        "ActivateOnClose" => Some(&["历史记录", "邻近标签页", "左侧标签页"]),
        "AlternateScroll" => Some(&["开", "关"]),
        "AutoIndentMode" => Some(&["语法感知", "保留缩进", "无"]),
        "AutosaveSettingDiscriminants" => Some(&["关闭", "延迟后", "焦点变化时", "窗口变化时"]),
        "BottomDockLayout" => Some(&["内嵌", "撑满", "左对齐", "右对齐"]),
        "BufferLineHeightDiscriminants" => Some(&["舒适", "标准", "自定义"]),
        "CliDefaultOpenBehavior" => Some(&["添加到现有窗口", "打开新窗口"]),
        "ClosePosition" => Some(&["左侧", "右侧"]),
        "CloseWindowWhenNoItems" => Some(&["跟随平台", "关闭窗口", "保持窗口打开"]),
        "CodeLens" => Some(&["关", "开", "菜单"]),
        "CompletionDetailAlignment" => Some(&["左对齐", "右对齐"]),
        "CompletionMenuItemKind" => Some(&["关", "符号"]),
        "CurrentLineHighlight" => Some(&["无", "边栏", "整行", "全部"]),
        "CursorShape" => Some(&["竖条", "方块", "下划线", "空心"]),
        "CursorShapeContent" => Some(&["方块", "下划线", "竖条", "空心"]),
        "DefaultOpenBehavior" => Some(&["添加到现有窗口", "打开新窗口"]),
        "DiagnosticSeverityContent" => Some(&["关", "错误", "警告", "信息", "提示", "全部"]),
        "DiffViewStyle" => Some(&["统一", "拆分"]),
        "DisplayIn" => Some(&["所有编辑器", "当前编辑器"]),
        "DockPosition" => Some(&["左侧", "底部", "右侧"]),
        "DockSide" => Some(&["左侧", "右侧"]),
        "DocumentColorsRenderMode" => Some(&["无", "内联", "边框", "背景"]),
        "DocumentFoldingRanges" => Some(&["关", "开"]),
        "DocumentSymbols" => Some(&["关", "开"]),
        "DoubleClickInMultibuffer" => Some(&["选中", "打开"]),
        "EditPredictionDataCollectionChoice" => Some(&["默认", "是", "否"]),
        "EditPredictionPromptFormatContent" => Some(&[
            "自动推断",
            "Zeta",
            "Zeta2",
            "Zeta2_1",
            "CodeLlama",
            "StarCoder",
            "DeepseekCoder",
            "Qwen",
            "CodeGemma",
            "Codestral",
            "Glm",
            "Sweep",
        ]),
        "EditPredictionsMode" => Some(&["微妙", "急切"]),
        "EncodingDisplayOptions" => Some(&["启用", "禁用", "非 UTF-8"]),
        "FormatOnSave" => Some(&["开", "关", "仅修改部分", "可用时仅修改部分"]),
        "GitGutterSetting" => Some(&["已跟踪文件", "隐藏"]),
        "GitHunkStyleSetting" => Some(&["已暂存空心", "未暂存空心"]),
        "GitPanelClickBehavior" => Some(&["项目差异", "文件差异", "查看文件"]),
        "GitPanelGroupBy" => Some(&["无", "按状态", "按暂存"]),
        "GitPanelSortBy" => Some(&["按路径", "按名称"]),
        "GitPathStyle" => Some(&["文件名优先", "文件路径优先"]),
        "GoToDefinitionFallback" => Some(&["无", "查找所有引用"]),
        "GoToDefinitionScrollStrategy" => Some(&["居中", "最小滚动", "顶部", "保持位置"]),
        "HideMouseMode" => Some(&["从不", "输入时", "输入和按键时"]),
        "IconThemeSelectionDiscriminants" => Some(&["静态", "动态"]),
        "ImageFileSizeUnit" => Some(&["二进制", "十进制"]),
        "IncludeIgnoredContent" => Some(&["全部", "已索引", "智能"]),
        "IndentGuideBackgroundColoring" => Some(&["禁用", "缩进感知"]),
        "IndentGuideColoring" => Some(&["禁用", "固定", "缩进感知"]),
        "InlineBlameLocation" => Some(&["行内", "状态栏"]),
        "LineEndingSetting" => Some(&["自动检测", "首选 LF", "首选 CRLF", "强制 LF", "强制 CRLF"]),
        "LspInsertMode" => Some(&["插入", "替换", "替换子序列", "替换后缀"]),
        "MinimapThumb" => Some(&["悬停时", "始终"]),
        "MinimapThumbBorder" => Some(&["完整", "左侧开放", "右侧开放", "仅左侧", "无"]),
        "ModeContent" => Some(&["普通", "插入"]),
        "MultiCursorModifier" => Some(&["Alt", "Cmd/Ctrl"]),
        "NotifyWhenAgentWaiting" => Some(&["主屏幕", "所有屏幕", "从不"]),
        "OnLastWindowClosed" => Some(&["跟随平台", "退出应用"]),
        "OpenResultsIn" => Some(&["多缓冲区", "选择器"]),
        "PaneSplitDirectionHorizontal" => Some(&["向上", "向下"]),
        "PaneSplitDirectionVertical" => Some(&["向左", "向右"]),
        "PlaySoundWhenAgentDone" => Some(&["从不", "隐藏时", "始终"]),
        "ProjectPanelEntrySpacing" => Some(&["舒适", "标准"]),
        "ProjectPanelSortMode" => Some(&["目录优先", "混合", "文件优先"]),
        "ProjectPanelSortOrder" => Some(&["默认", "大写优先", "小写优先", "Unicode"]),
        "ReduceMotionMode" => Some(&["开", "关"]),
        "RelativeLineNumbers" => Some(&["禁用", "启用", "换行行"]),
        "RestoreOnStartupBehavior" => Some(&["空标签页", "上次工作区", "上次会话", "启动面板"]),
        "RewrapBehavior" => Some(&["注释中", "选区内", "任意位置"]),
        "ScanSymlinksSetting" => Some(&["始终", "已展开时"]),
        "ScrollBeyondLastLine" => Some(&["关", "一页", "垂直滚动边距"]),
        "ScrollbarDiagnostics" => Some(&["全部", "信息", "警告", "错误", "无"]),
        "SeedQuerySetting" => Some(&["始终", "选区", "从不"]),
        "SemanticTokens" => Some(&["关", "组合", "完整"]),
        "ShellDiscriminants" => Some(&["系统默认", "指定程序", "带参数"]),
        "ShowCloseButton" => Some(&["始终", "悬停时", "隐藏"]),
        "ShowDiagnostics" => Some(&["关", "仅错误", "全部"]),
        "ShowIndentGuides" => Some(&["始终", "从不"]),
        "ShowMinimap" => Some(&["自动", "始终", "从不"]),
        "ShowScrollbar" => Some(&["自动", "跟随系统", "始终", "从不"]),
        "ShowWhitespaceSetting" => Some(&["选区内", "无", "全部", "边界", "行尾"]),
        "SidebarDockPosition" => Some(&["左侧", "右侧"]),
        "SnippetSortOrder" => Some(&["顶部", "内联", "底部", "无"]),
        "SoftWrap" => Some(&["无", "按首选行宽", "按编辑器宽度", "按限定宽度"]),
        "StatusStyle" => Some(&["图标", "标签颜色"]),
        "SteppingGranularity" => Some(&["语句", "行", "指令"]),
        "TerminalBell" => Some(&["系统默认", "关"]),
        "TerminalBlink" => Some(&["关", "跟随终端", "开"]),
        "TerminalDockPosition" => Some(&["左侧", "底部", "右侧"]),
        "TextRenderingMode" => Some(&["跟随平台", "次像素", "灰度"]),
        "ThemeAppearanceMode" => Some(&["浅色", "深色", "跟随系统"]),
        "ThemeSelectionDiscriminants" => Some(&["静态", "动态"]),
        "ThinkingBlockDisplay" => Some(&["自动", "预览", "始终展开", "始终折叠"]),
        "UseSystemClipboard" => Some(&["从不", "始终", "复制时"]),
        "VimInsertModeCursorShape" => Some(&["继承", "竖条", "方块", "下划线", "空心"]),
        "WindowButtonLayoutContentDiscriminants" => Some(&["跟随平台", "标准", "自定义"]),
        "WindowDecorations" => Some(&["客户端", "服务端"]),
        "WordsCompletionMode" => Some(&["启用", "回退", "禁用"]),
        "WorkingDirectoryDiscriminants" => Some(&[
            "当前文件目录",
            "当前项目目录",
            "第一个项目目录",
            "始终为主目录",
            "始终",
        ]),
        _ => None,
    }
}
